apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: istio-success-rate
spec:
  # this analysis template requires a service name and namespace to be supplied to the query
  args:
  - name: service
  - name: namespace
  metrics:
  - name: success-rate
    initialDelay: 60s
    interval: 20s
    successCondition: result[0] > 0.90
    provider:
      prometheus:
        #address: http://prometheus.aks-istio-system.svc.cluster.local:9090
        address: http://10.244.1.81:9090
        query: >+
          sum(irate(istio_requests_total{
            reporter="source",
            destination_service=~"{{args.service}}.{{args.namespace}}.svc.cluster.local",
            response_code!~"5.*"}[40s])
          )
          /
          sum(irate(istio_requests_total{
            reporter="source",
            destination_service=~"{{args.service}}.{{args.namespace}}.svc.cluster.local"}[40s])
          )
  # - name: latency
  #   initialDelay: 60s
  #   interval: 20s
  #   successCondition: result[0] < 0.5
  #   provider:
  #     prometheus:
  #       address: http://10.244.2.168:9090
  #       query: >+
  #         histogram_quantile(0.95, sum(rate(istio_request_duration_seconds_bucket{
  #           reporter="source",
  #           destination_service=~"{{args.service}}.{{args.namespace}}.svc.cluster.local"}[40s])
  #         ) by (le))
